version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - backend
    command: sh -c "npx prisma migrate deploy && node dist/main.js"

  db:
    image: postgres:15
    container_name: pg_expenses
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: expenses
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_expenses
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  pg_data:

networks:
  backend:
    driver: bridge
